== Normative references

The following normative documents contain provisions which, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. However, parties to agreements based on this document are encouraged to investigate the possibility of applying the most recent editions of the normative documents indicated below. For undated references, the latest edition of the normative document referred to applies.

Items in this list are liked to their full citation <<Bibliography>>.

* <<OGC06-103r4>>, _OGC 06-103r4, OpenGIS Implementation Standard for Geographic information — Simple feature access — Part 1: Common architecture_ (also available from ISO: <<ISO19125-1>>)

* <<OGC10-004r3>>, _OGC 10-004r3, Geographic information  — Observations and measurements_ (also available from ISO: <<ISO19156>>)

* <<OGC07-036>>, _OGC 07-036: Geography Markup Language (GML) Encoding Standard_

* <<IETF3987>>, Internet Engineering Task Force, _RFC 3987: Internationalized Resource Identifiers (IRIs)_

* <<OWL2>> _OWL 2 Web Ontology Language Document Overview (Second Edition)_

* <<RDF>>, _RDF 1.1 Concepts and Abstract Syntax_

* <<RDFS>> _RDF Schema 1.1_

* <<RIFCORE>>, _RIF Core Dialect (Second Edition)_

* <<SPARQL>>, _SPARQL 1.1 Query Language_

* <<SPARQLENT>>, _SPARQL 1.1 Entailment Regimes_

* <<SPARQLPROT>>, _SPARQL 1.1 Protocol_

* <<SPARQLRESX>>, _SPARQL Query Results XML Format (Second Edition)_

* <<SPARQLRESJ>>, _SPARQL 1.1 Query Results JSON Format_
